fix(build): add missing errno.h includes for Linux build
The 6th macOS scan fixes added errno usage to tar_create.c and
json_parser.c but forgot to include <errno.h>, causing Linux build
failures:

  tar_create.c:285:28: error: 'errno' undeclared
  note: 'errno' is defined in header '<errno.h>'

Added missing includes:
- tar_create.c: Added #include <errno.h>
- json_parser.c: Added #include <errno.h>

Note: stub_repack.c already had errno.h included.