fix(windows): add missing headers and ssize_t typedef
The Windows build was failing with multiple errors in file_io_common.h:

1. strlen() undeclared:
   file_io_common.h(94,35): error: call to undeclared library
   function 'strlen'

2. ssize_t unknown type:
   file_io_common.h(123,15): error: unknown type name 'ssize_t'
   file_io_common.h(145,15): error: unknown type name 'ssize_t'

3. ftello() undeclared in stub_repack.c and binject.c:
   error: call to undeclared function 'ftello'

Fixes:
- Added #include <string.h> for strlen()
- Added #include <sys/types.h> for Windows
- Added typedef intptr_t ssize_t for Windows (POSIX type not available)
- ftello macro already defined but needs sys/types.h for intptr_t